services:
  postgres-12.1-alpine:
    container_name: "postgres"
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: <default user pwd>
    ports:
      - "6000:5432"
    volumes:
      - <local folder path>:/var/lib/postgresql/data
