version: '3.8'

services:

  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:  
      POSTGRES_PASSWORD:
    ports:
      - "6000:5432"
    volumes:
      - <local folder path>:/var/lib/postgresql/data