version: '3.8'

services:

  postgres-12.1-alpine:
    container_name: 'postgres-12.1-alpine'
    image: 'postgres:12.1-alpine'
    environment:  
      POSTGRES_PASSWORD:<default password>
    ports:
      - "6000:5432"
    volumes:
      - <localfolderpath>/var/lib/postgresql/data